//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//     Version: 2.2.7.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Reflection;
using System.Data;
using System.Data.SqlClient;
using Storm.Lib;
using Storm.Attributes;
using HsrOrderApp.BusinessLayer.DomainModel;

namespace HsrOrderApp.BusinessLayer.DataMapper
{


	[MapperImpl(typeof(Address))]
	public class AddressMapper : IMapper
	{		
#region Finder Methods
		public DomainObject findById(Key id)
		{
			try
			{
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from Addresses WHERE AddressID = @AddressId";
				SqlCommand command = new SqlCommand(sqlStmt, connection);
				command.Parameters.Add("@AddressId", id[0]);

				reader = command.ExecuteReader();
				Address address = null;
				if(reader.Read())
				{
					address = loadFields(reader);
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return address;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList findAll()
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from Addresses";
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList find(QueryObject qo)
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from Addresses WHERE " + qo.ToString();
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		
#endregion		
		
#region IMapper Members
		public void insert(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				Address address = (Address)subject;
				SqlCommand command = new SqlCommand(
					"INSERT INTO Addresses (Email, Street, City, PersonID, Phone, PostalCode) VALUES (@Email, @Street, @City, @Person, @Phone, @PostalCode) ; SELECT AddressID, chTimeStamp FROM Addresses WHERE AddressID = SCOPE_IDENTITY()",
					connection, transaction);

				if(subject.isNull("Email"))
				{
					command.Parameters.Add("@Email", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Email", address.Email);
				}
				if(subject.isNull("Street"))
				{
					command.Parameters.Add("@Street", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Street", address.Street);
				}
				if(subject.isNull("City"))
				{
					command.Parameters.Add("@City", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@City", address.City);
				}
				if(subject.isNull("Person") || address.Person.isNull("PersonId"))
				{
					command.Parameters.Add("@Person", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Person", address.Person.PersonId);
				}
				if(subject.isNull("Phone"))
				{
					command.Parameters.Add("@Phone", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Phone", address.Phone);
				}
				if(subject.isNull("PostalCode"))
				{
					command.Parameters.Add("@PostalCode", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@PostalCode", address.PostalCode);
				}
				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					address.Id = new Key(new object[] {
						safeGetInt32(reader, "AddressID")});
					address.Timestamp = safeGetTimestamp(reader);
					subject.FireIdChanged();
					reader.Close();			
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void update(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				Address address = (Address)subject;
				SqlCommand command = new SqlCommand(
					"UPDATE Addresses SET Email = @Email, Street = @Street, City = @City, PersonID = @Person, Phone = @Phone, PostalCode = @PostalCode WHERE AddressID = @AddressId AND chTimeStamp = @chTimeStamp IF @@ROWCOUNT > 0  BEGIN SELECT chTimeStamp FROM Addresses WHERE AddressID = @AddressId END",
					connection, transaction); 

				command.Parameters.Add("@chTimeStamp", address.Timestamp.Value);
				if(subject.isNull("AddressId"))
				{
					command.Parameters.Add("@AddressId", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@AddressId", address.AddressId);
				}
				if(subject.isNull("Email"))
				{
					command.Parameters.Add("@Email", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Email", address.Email);
				}
				if(subject.isNull("Street"))
				{
					command.Parameters.Add("@Street", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Street", address.Street);
				}
				if(subject.isNull("City"))
				{
					command.Parameters.Add("@City", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@City", address.City);
				}
				if(subject.isNull("Person") || address.Person.isNull("PersonId"))
				{
					command.Parameters.Add("@Person", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Person", address.Person.Id[0]);
				}
				if(subject.isNull("Phone"))
				{
					command.Parameters.Add("@Phone", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Phone", address.Phone);
				}
				if(subject.isNull("PostalCode"))
				{
					command.Parameters.Add("@PostalCode", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@PostalCode", address.PostalCode);
				}

				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					address.Timestamp = safeGetTimestamp(reader);
					reader.Close();
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
				subject.FireIdChanged();

			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void delete(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				Address address = (Address)subject;
				
				SqlCommand command = new SqlCommand(
					"DELETE FROM Addresses WHERE AddressID = @AddressId AND chTimeStamp = @chTimeStamp",
					connection, transaction);

				command.Parameters.Add("@chTimeStamp", address.Timestamp.Value);
				if(subject.isNull("AddressId"))
				{
					command.Parameters.Add("@AddressId", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@AddressId", address.AddressId);
				}
				if(command.ExecuteNonQuery() <= 0)
				{
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public DomainObject ResolveToOneRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			SqlConnection connection = UnitOfWork.Instance.Connection;
			
			connection.Open();

			try
			{
				String selectStmt = "SELECT * FROM Addresses WHERE " + fieldName + " = @FK";
				SqlCommand command = new SqlCommand(selectStmt, connection);
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				Address address = null;
				
				if(reader.Read())
				{
					address = loadFields(reader);
				}
				if(reader != null)
				{
					reader.Close();
				}
				connection.Close();
				
				return address;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
		}
		
		public IList ResolveToManyRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			ArrayList array = new ArrayList();
			SqlConnection connection = UnitOfWork.Instance.Connection;
			SqlCommand command;
			connection.Open();
			
			try
			{
				command = new SqlCommand(
					"SELECT AddressID, chTimeStamp FROM Addresses WHERE " + fieldName + " = @FK", connection);
					
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				ArrayList keys = new ArrayList();
				Timestamp timestamp;
				while(reader.Read())
				{ 
					object addressid = safeGetValue(reader, "AddressID");
					
					timestamp = safeGetTimestamp(reader);
					
					Key currentKey = new Key(new object[]{addressid});
					DomainObject domobj = UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(
						typeof(Address), currentKey);
					
					if(domobj == null)
					{
						keys.Add(currentKey);
					}
					else if(!domobj.Timestamp.Equals(timestamp))
					{
						UnitOfWork.Instance.IdentityMap.unregisterDomainObject(domobj);
						keys.Add(currentKey);
					}
					else
					{
						array.Add(domobj);
					}
				}
				reader.Close();

				if(keys.Count > 0)
				{
					int primKeysCount = 1;
					ArrayList primKeys = new ArrayList();
					primKeys.Add("AddressID");
					StringBuilder selectAdStmt = new StringBuilder();
					selectAdStmt.Append("SELECT * FROM ");
					selectAdStmt.Append("Addresses");
					selectAdStmt.Append(" WHERE ");
					StringBuilder whereStmt;
					String[] andStmts = new String[keys.Count];
					for(int i = 0; i < keys.Count; i++)
					{
						String[] primKeyCriterias = new String[primKeysCount];
						for(int j = 0; j < primKeysCount; j++)
						{
							primKeyCriterias[j] = primKeys[j] + " = @key" + i +j;
						}
						whereStmt = new StringBuilder();
						whereStmt.Append("(");
						whereStmt.Append(String.Join(" AND ", primKeyCriterias));
						whereStmt.Append(")");
						andStmts[i] = whereStmt.ToString();
					}
					selectAdStmt.Append(String.Join(" OR ", andStmts));
					
					command = new SqlCommand(
						selectAdStmt.ToString(), connection);
					for(int i = 0; i < keys.Count; i++)
					{
						for(int j = 0; j < primKeysCount; j++)
						{
							String keyParam = "@key" + i + j;
							command.Parameters.Add(keyParam, ((Key)keys[i])[j]);
						}
					}
					
					reader = command.ExecuteReader();
					
					while(reader.Read())
					{
						Address address = loadFields(reader);
						array.Add(address);
					}
					reader.Close();
				} 
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
			return array;
		}
#endregion		
		
#region Helper Methods
		public Address loadFields(SqlDataReader reader)
		{
			Timestamp m_timestamp = safeGetTimestamp(reader);
			Key m_key = new Key(new object[]{
				safeGetValue(reader, "AddressID")
			});
		
			object m_City = safeGetString(reader, "City");
			object m_Street = safeGetString(reader, "Street");
			object m_PostalCode = safeGetString(reader, "PostalCode");
			object m_Phone = safeGetString(reader, "Phone");
			object m_Email = safeGetString(reader, "Email");
		
			Address address = 
				(Address)UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(typeof(Address), m_key);
			
			if(address == null)
			{
				address = 
					(Address)Registry.Instance.getFactory(typeof(Address)).createFromParameters(
						m_key,
						m_timestamp,
						new DictionaryEntry("Person", new ToOneRelation(typeof(Person), "PersonID", new Key(new object[] { safeGetValue(reader, "PersonID")}))),
						new DictionaryEntry("City", m_City),
						new DictionaryEntry("Street", m_Street),
						new DictionaryEntry("PostalCode", m_PostalCode),
						new DictionaryEntry("Phone", m_Phone),
						new DictionaryEntry("Email", m_Email));
				
				UnitOfWork.Instance.IdentityMap.registerDomainObject(address);
			}
			return address;
		}

		protected Timestamp safeGetTimestamp(SqlDataReader reader)
		{
			byte[] m_buffer = new byte[8];
			reader.GetBytes(reader.GetOrdinal("chTimeStamp"), 0, m_buffer, 0, 8);
			return new Timestamp(m_buffer);
		}
		
		protected object safeGetString(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : reader.GetString(ordinal).Trim();
		}
		
		protected object safeGetDouble(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDouble(ordinal);
		}
		
		protected object safeGetInt32(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetInt32(ordinal);
		}
		
		protected object safeGetDateTime(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDateTime(ordinal);
		}

		protected object safeGetValue(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetValue(ordinal);
		}
#endregion

	}
}
