//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//     Version: 2.2.7.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Reflection;
using System.Data;
using System.Data.SqlClient;
using Storm.Lib;
using Storm.Attributes;
using HsrOrderApp.BusinessLayer.DomainModel;

namespace HsrOrderApp.BusinessLayer.DataMapper
{


	[MapperImpl(typeof(OrderDetail))]
	public class OrderDetailMapper : IMapper
	{		
#region Finder Methods
		public DomainObject findById(Key id)
		{
			try
			{
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from OrderDetails WHERE OrderID = @Order AND ProductID = @Product";
				SqlCommand command = new SqlCommand(sqlStmt, connection);
				command.Parameters.Add("@Order", id[0]);
				command.Parameters.Add("@Product", id[1]);

				reader = command.ExecuteReader();
				OrderDetail orderdetail = null;
				if(reader.Read())
				{
					orderdetail = loadFields(reader);
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return orderdetail;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList findAll()
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from OrderDetails";
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList find(QueryObject qo)
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from OrderDetails WHERE " + qo.ToString();
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		
#endregion		
		
#region IMapper Members
		public void insert(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				OrderDetail orderdetail = (OrderDetail)subject;
				SqlCommand command = new SqlCommand(
					"INSERT INTO OrderDetails (Quantity, UnitPrice, OrderID, ProductID) VALUES (@Quantity, @UnitPrice, @Order, @Product) ; SELECT chTimestamp FROM OrderDetails WHERE OrderID= @Order AND ProductID= @Product",
					connection, transaction);

				if(subject.isNull("Quantity"))
				{
					command.Parameters.Add("@Quantity", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Quantity", orderdetail.Quantity);
				}
				if(subject.isNull("UnitPrice"))
				{
					command.Parameters.Add("@UnitPrice", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@UnitPrice", orderdetail.UnitPrice);
				}
				if(subject.isNull("Order") || orderdetail.Order.isNull("OrderId"))
				{
					command.Parameters.Add("@Order", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Order", orderdetail.Order.OrderId);
				}
				if(subject.isNull("Product") || orderdetail.Product.isNull("ProductId"))
				{
					command.Parameters.Add("@Product", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Product", orderdetail.Product.ProductId);
				}
				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					orderdetail.Timestamp = safeGetTimestamp(reader);
					subject.FireIdChanged();
					reader.Close();			
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void update(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				OrderDetail orderdetail = (OrderDetail)subject;
				SqlCommand command = new SqlCommand(
					"UPDATE OrderDetails SET UnitPrice = @UnitPrice, Quantity = @Quantity WHERE OrderID = @Order AND ProductID = @Product AND chTimestamp = @chTimestamp IF @@ROWCOUNT > 0  BEGIN SELECT chTimestamp FROM OrderDetails WHERE OrderID = @Order AND ProductID = @Product END",
					connection, transaction); 

				command.Parameters.Add("@chTimestamp", orderdetail.Timestamp.Value);
				if(subject.isNull("Order") || orderdetail.Order.isNull("OrderId"))
				{
					command.Parameters.Add("@Order", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Order", orderdetail.Order.Id[0]);
				}
				if(subject.isNull("Product") || orderdetail.Product.isNull("ProductId"))
				{
					command.Parameters.Add("@Product", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Product", orderdetail.Product.Id[0]);
				}
				if(subject.isNull("UnitPrice"))
				{
					command.Parameters.Add("@UnitPrice", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@UnitPrice", orderdetail.UnitPrice);
				}
				if(subject.isNull("Quantity"))
				{
					command.Parameters.Add("@Quantity", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Quantity", orderdetail.Quantity);
				}

				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					orderdetail.Timestamp = safeGetTimestamp(reader);
					reader.Close();
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
				subject.FireIdChanged();

			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void delete(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				OrderDetail orderdetail = (OrderDetail)subject;
				
				SqlCommand command = new SqlCommand(
					"DELETE FROM OrderDetails WHERE OrderID = @Order AND ProductID = @Product AND chTimestamp = @chTimestamp",
					connection, transaction);

				command.Parameters.Add("@chTimestamp", orderdetail.Timestamp.Value);
				if(subject.isNull("Order") || orderdetail.Order.isNull("OrderId"))
				{
					command.Parameters.Add("@Order", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Order", orderdetail.Order.Id[0]);
				}
				if(subject.isNull("Product") || orderdetail.Product.isNull("ProductId"))
				{
					command.Parameters.Add("@Product", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Product", orderdetail.Product.Id[0]);
				}
				if(command.ExecuteNonQuery() <= 0)
				{
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public DomainObject ResolveToOneRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			SqlConnection connection = UnitOfWork.Instance.Connection;
			
			connection.Open();

			try
			{
				String selectStmt = "SELECT * FROM OrderDetails WHERE " + fieldName + " = @FK";
				SqlCommand command = new SqlCommand(selectStmt, connection);
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				OrderDetail orderdetail = null;
				
				if(reader.Read())
				{
					orderdetail = loadFields(reader);
				}
				if(reader != null)
				{
					reader.Close();
				}
				connection.Close();
				
				return orderdetail;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
		}
		
		public IList ResolveToManyRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			ArrayList array = new ArrayList();
			SqlConnection connection = UnitOfWork.Instance.Connection;
			SqlCommand command;
			connection.Open();
			
			try
			{
				command = new SqlCommand(
					"SELECT OrderID, ProductID, chTimestamp FROM OrderDetails WHERE " + fieldName + " = @FK", connection);
					
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				ArrayList keys = new ArrayList();
				Timestamp timestamp;
				while(reader.Read())
				{ 
					object order = safeGetValue(reader, "OrderID");
					object product = safeGetValue(reader, "ProductID");
					
					timestamp = safeGetTimestamp(reader);
					
					Key currentKey = new Key(new object[]{order, product});
					DomainObject domobj = UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(
						typeof(OrderDetail), currentKey);
					
					if(domobj == null)
					{
						keys.Add(currentKey);
					}
					else if(!domobj.Timestamp.Equals(timestamp))
					{
						UnitOfWork.Instance.IdentityMap.unregisterDomainObject(domobj);
						keys.Add(currentKey);
					}
					else
					{
						array.Add(domobj);
					}
				}
				reader.Close();

				if(keys.Count > 0)
				{
					int primKeysCount = 2;
					ArrayList primKeys = new ArrayList();
					primKeys.Add("OrderID");
					primKeys.Add("ProductID");
					StringBuilder selectAdStmt = new StringBuilder();
					selectAdStmt.Append("SELECT * FROM ");
					selectAdStmt.Append("OrderDetails");
					selectAdStmt.Append(" WHERE ");
					StringBuilder whereStmt;
					String[] andStmts = new String[keys.Count];
					for(int i = 0; i < keys.Count; i++)
					{
						String[] primKeyCriterias = new String[primKeysCount];
						for(int j = 0; j < primKeysCount; j++)
						{
							primKeyCriterias[j] = primKeys[j] + " = @key" + i +j;
						}
						whereStmt = new StringBuilder();
						whereStmt.Append("(");
						whereStmt.Append(String.Join(" AND ", primKeyCriterias));
						whereStmt.Append(")");
						andStmts[i] = whereStmt.ToString();
					}
					selectAdStmt.Append(String.Join(" OR ", andStmts));
					
					command = new SqlCommand(
						selectAdStmt.ToString(), connection);
					for(int i = 0; i < keys.Count; i++)
					{
						for(int j = 0; j < primKeysCount; j++)
						{
							String keyParam = "@key" + i + j;
							command.Parameters.Add(keyParam, ((Key)keys[i])[j]);
						}
					}
					
					reader = command.ExecuteReader();
					
					while(reader.Read())
					{
						OrderDetail orderdetail = loadFields(reader);
						array.Add(orderdetail);
					}
					reader.Close();
				} 
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
			return array;
		}
#endregion		
		
#region Helper Methods
		public OrderDetail loadFields(SqlDataReader reader)
		{
			Timestamp m_timestamp = safeGetTimestamp(reader);
			Key m_key = new Key(new object[]{
				safeGetValue(reader, "OrderID"),
				safeGetValue(reader, "ProductID")
			});
		
			object m_UnitPrice = safeGetDouble(reader, "UnitPrice");
			object m_Quantity = safeGetInt32(reader, "Quantity");
		
			OrderDetail orderdetail = 
				(OrderDetail)UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(typeof(OrderDetail), m_key);
			
			if(orderdetail == null)
			{
				orderdetail = 
					(OrderDetail)Registry.Instance.getFactory(typeof(OrderDetail)).createFromParameters(
						m_key,
						m_timestamp,
						new DictionaryEntry("Order", new ToOneRelation(typeof(Order), "OrderID", new Key(new object[] { safeGetValue(reader, "OrderID")}))),
						new DictionaryEntry("Product", new ToOneRelation(typeof(Product), "ProductID", new Key(new object[] { safeGetValue(reader, "ProductID")}))),
						new DictionaryEntry("UnitPrice", m_UnitPrice),
						new DictionaryEntry("Quantity", m_Quantity));
				
				UnitOfWork.Instance.IdentityMap.registerDomainObject(orderdetail);
			}
			return orderdetail;
		}

		protected Timestamp safeGetTimestamp(SqlDataReader reader)
		{
			byte[] m_buffer = new byte[8];
			reader.GetBytes(reader.GetOrdinal("chTimestamp"), 0, m_buffer, 0, 8);
			return new Timestamp(m_buffer);
		}
		
		protected object safeGetString(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : reader.GetString(ordinal).Trim();
		}
		
		protected object safeGetDouble(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDouble(ordinal);
		}
		
		protected object safeGetInt32(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetInt32(ordinal);
		}
		
		protected object safeGetDateTime(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDateTime(ordinal);
		}

		protected object safeGetValue(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetValue(ordinal);
		}
#endregion

	}
}
