//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//     Version: 2.2.7.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Reflection;
using System.Data;
using System.Data.SqlClient;
using Storm.Lib;
using Storm.Attributes;
using HsrOrderApp.BusinessLayer.DomainModel;

namespace HsrOrderApp.BusinessLayer.DataMapper
{


	[MapperImpl(typeof(Person))]
	public class PersonMapper : IMapper
	{		
#region Finder Methods
		public DomainObject findById(Key id)
		{
			try
			{
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from Persons WHERE PersonID = @PersonId";
				SqlCommand command = new SqlCommand(sqlStmt, connection);
				command.Parameters.Add("@PersonId", id[0]);

				reader = command.ExecuteReader();
				Person person = null;
				if(reader.Read())
				{
					person = loadFields(reader);
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return person;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList findAll()
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from Persons";
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList find(QueryObject qo)
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from Persons WHERE " + qo.ToString();
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		
#endregion		
		
#region IMapper Members
		public void insert(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				Person person = (Person)subject;
				SqlCommand command = new SqlCommand(
					"INSERT INTO Persons (Password, Name) VALUES (@Password, @Name) ; SELECT PersonID, chTimestamp FROM Persons WHERE PersonID = SCOPE_IDENTITY()",
					connection, transaction);

				if(subject.isNull("Password"))
				{
					command.Parameters.Add("@Password", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Password", person.Password);
				}
				if(subject.isNull("Name"))
				{
					command.Parameters.Add("@Name", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Name", person.Name);
				}
				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					person.Id = new Key(new object[] {
						safeGetInt32(reader, "PersonID")});
					person.Timestamp = safeGetTimestamp(reader);
					subject.FireIdChanged();
					reader.Close();			
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void update(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				Person person = (Person)subject;
				SqlCommand command = new SqlCommand(
					"UPDATE Persons SET Password = @Password, Name = @Name WHERE PersonID = @PersonId AND chTimestamp = @chTimestamp IF @@ROWCOUNT > 0  BEGIN SELECT chTimestamp FROM Persons WHERE PersonID = @PersonId END",
					connection, transaction); 

				command.Parameters.Add("@chTimestamp", person.Timestamp.Value);
				if(subject.isNull("PersonId"))
				{
					command.Parameters.Add("@PersonId", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@PersonId", person.PersonId);
				}
				if(subject.isNull("Password"))
				{
					command.Parameters.Add("@Password", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Password", person.Password);
				}
				if(subject.isNull("Name"))
				{
					command.Parameters.Add("@Name", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Name", person.Name);
				}

				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					person.Timestamp = safeGetTimestamp(reader);
					reader.Close();
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
				subject.FireIdChanged();

			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void delete(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				Person person = (Person)subject;
				
				SqlCommand command = new SqlCommand(
					"DELETE FROM Persons WHERE PersonID = @PersonId AND chTimestamp = @chTimestamp",
					connection, transaction);

				command.Parameters.Add("@chTimestamp", person.Timestamp.Value);
				if(subject.isNull("PersonId"))
				{
					command.Parameters.Add("@PersonId", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@PersonId", person.PersonId);
				}
				if(command.ExecuteNonQuery() <= 0)
				{
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public DomainObject ResolveToOneRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			SqlConnection connection = UnitOfWork.Instance.Connection;
			
			connection.Open();

			try
			{
				String selectStmt = "SELECT * FROM Persons WHERE " + fieldName + " = @FK";
				SqlCommand command = new SqlCommand(selectStmt, connection);
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				Person person = null;
				
				if(reader.Read())
				{
					person = loadFields(reader);
				}
				if(reader != null)
				{
					reader.Close();
				}
				connection.Close();
				
				return person;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
		}
		
		public IList ResolveToManyRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			ArrayList array = new ArrayList();
			SqlConnection connection = UnitOfWork.Instance.Connection;
			SqlCommand command;
			connection.Open();
			
			try
			{
				command = new SqlCommand(
					"SELECT PersonID, chTimestamp FROM Persons WHERE " + fieldName + " = @FK", connection);
					
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				ArrayList keys = new ArrayList();
				Timestamp timestamp;
				while(reader.Read())
				{ 
					object personid = safeGetValue(reader, "PersonID");
					
					timestamp = safeGetTimestamp(reader);
					
					Key currentKey = new Key(new object[]{personid});
					DomainObject domobj = UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(
						typeof(Person), currentKey);
					
					if(domobj == null)
					{
						keys.Add(currentKey);
					}
					else if(!domobj.Timestamp.Equals(timestamp))
					{
						UnitOfWork.Instance.IdentityMap.unregisterDomainObject(domobj);
						keys.Add(currentKey);
					}
					else
					{
						array.Add(domobj);
					}
				}
				reader.Close();

				if(keys.Count > 0)
				{
					int primKeysCount = 1;
					ArrayList primKeys = new ArrayList();
					primKeys.Add("PersonID");
					StringBuilder selectAdStmt = new StringBuilder();
					selectAdStmt.Append("SELECT * FROM ");
					selectAdStmt.Append("Persons");
					selectAdStmt.Append(" WHERE ");
					StringBuilder whereStmt;
					String[] andStmts = new String[keys.Count];
					for(int i = 0; i < keys.Count; i++)
					{
						String[] primKeyCriterias = new String[primKeysCount];
						for(int j = 0; j < primKeysCount; j++)
						{
							primKeyCriterias[j] = primKeys[j] + " = @key" + i +j;
						}
						whereStmt = new StringBuilder();
						whereStmt.Append("(");
						whereStmt.Append(String.Join(" AND ", primKeyCriterias));
						whereStmt.Append(")");
						andStmts[i] = whereStmt.ToString();
					}
					selectAdStmt.Append(String.Join(" OR ", andStmts));
					
					command = new SqlCommand(
						selectAdStmt.ToString(), connection);
					for(int i = 0; i < keys.Count; i++)
					{
						for(int j = 0; j < primKeysCount; j++)
						{
							String keyParam = "@key" + i + j;
							command.Parameters.Add(keyParam, ((Key)keys[i])[j]);
						}
					}
					
					reader = command.ExecuteReader();
					
					while(reader.Read())
					{
						Person person = loadFields(reader);
						array.Add(person);
					}
					reader.Close();
				} 
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
			return array;
		}
#endregion		
		
#region Helper Methods
		public Person loadFields(SqlDataReader reader)
		{
			Timestamp m_timestamp = safeGetTimestamp(reader);
			Key m_key = new Key(new object[]{
				safeGetValue(reader, "PersonID")
			});
		
			object m_Name = safeGetString(reader, "Name");
			object m_Password = safeGetString(reader, "Password");
		
			Person person = 
				(Person)UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(typeof(Person), m_key);
			
			if(person == null)
			{
				person = 
					(Person)Registry.Instance.getFactory(typeof(Person)).createFromParameters(
						m_key,
						m_timestamp,
						new DictionaryEntry("Name", m_Name),
						new DictionaryEntry("Password", m_Password),
						new DictionaryEntry("Addresses", new ToManyRelation(typeof(Address), "PersonID", m_key, false)),
						new DictionaryEntry("Orders", new ToManyRelation(typeof(Order), "PersonID", m_key, false)));
				
				UnitOfWork.Instance.IdentityMap.registerDomainObject(person);
			}
			return person;
		}

		protected Timestamp safeGetTimestamp(SqlDataReader reader)
		{
			byte[] m_buffer = new byte[8];
			reader.GetBytes(reader.GetOrdinal("chTimestamp"), 0, m_buffer, 0, 8);
			return new Timestamp(m_buffer);
		}
		
		protected object safeGetString(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : reader.GetString(ordinal).Trim();
		}
		
		protected object safeGetDouble(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDouble(ordinal);
		}
		
		protected object safeGetInt32(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetInt32(ordinal);
		}
		
		protected object safeGetDateTime(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDateTime(ordinal);
		}

		protected object safeGetValue(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetValue(ordinal);
		}
#endregion

	}
}
