//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//     Version: 2.2.7.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Reflection;
using Storm.Lib;
using Storm.Attributes;
using HsrOrderApp.BusinessLayer.DomainModel;

namespace HsrOrderApp.BusinessLayer.DomainModelImpl
{

	[DomainObjectImpl]
	public class OrderImpl : Order
	{
#region Factory Implementation
		public class FactoryImpl : OrderFactory, IFactory
		{ 
			public override Order createOrder(Person person, DateTime orderDate, DateTime shippedDate, String orderState)
			{
				return new OrderImpl(person, orderDate, shippedDate, orderState);
			}
			
			public DomainObject create()
			{
				return new OrderImpl();
			}
			
			public DomainObject createFromParameters(
				Key id,
				Timestamp timestamp,
				params DictionaryEntry[] parameters)
			{
				return new OrderImpl(id, timestamp, parameters);
			}
		}
#endregion

#region Finder Implementation
		public class FinderImpl : OrderFinder, IFinder
		{
			public override IList findByOrderDate(DateTime orderDate)
			{
				QueryObject qo = new QueryObject();
				qo.addCriteria(new Criteria(Criteria.Operator.Equal, "OrderDate", orderDate));

				return Registry.Instance.getMapper(typeof(Order)).find(qo);
			}
			public DomainObject findById(Key id)
			{
				return Registry.Instance.getMapper(typeof(Order)).findById(id);
			}
			public IList find(QueryObject qo)
			{
				return Registry.Instance.getMapper(typeof(Order)).find(qo);
			}
			public IList findAll()
			{
				return Registry.Instance.getMapper(typeof(Order)).findAll();
			}
		}
#endregion

#region Static Attributes
		private static FactoryImpl m_FactoryImpl = new FactoryImpl();
		private static FinderImpl m_FinderImpl = new FinderImpl();
#endregion
		
#region Member Variables
		private ToOneRelation m_Person = null;
		private object m_OrderDate = null;
		private object m_ShippedDate = null;
		private object m_OrderState = null;
		private ToManyRelation m_OrderDetails = null;
#endregion

#region Constructors
		public OrderImpl()
		{
		}
		
		public OrderImpl(Person person, DateTime orderDate, DateTime shippedDate, String orderState)
		{
			markNew();
			m_Person = new ToOneRelation(typeof(Person), "PersonID", null);
			m_OrderDetails = new ToManyRelation(typeof(OrderDetail), "OrderID", null, true);
			m_ShippedDate = shippedDate;
			m_OrderState = orderState;
			m_OrderDate = orderDate;
			m_Person.Object = person;
		}

		internal OrderImpl(
			Key id, 
			Timestamp timestamp, 
			params DictionaryEntry[] parameters)
		{ 
			markClean();
			m_id = id;
			m_timestamp = timestamp;
			FieldInfo fInfo;
			Type thisType = this.GetType();
			Type domainObjectType = typeof(Order);
			
			IEnumerator enumerator = parameters.GetEnumerator();

			while(enumerator.MoveNext())
			{
				if(((DictionaryEntry)enumerator.Current).Value != null)
				{
					if(((DictionaryEntry)enumerator.Current).Value.GetType() == typeof(ToOneRelation))
					{ 
						if((String)((DictionaryEntry)enumerator.Current).Key == "Person")
						{ 
							m_Person = (ToOneRelation)((DictionaryEntry)enumerator.Current).Value;
							continue;
						}
					} 
					if(((DictionaryEntry)enumerator.Current).Value.GetType() == typeof(ToManyRelation))
					{ 
						if((String)((DictionaryEntry)enumerator.Current).Key == "OrderDetails")
						{ 
							m_OrderDetails = (ToManyRelation)((DictionaryEntry)enumerator.Current).Value;
							continue;
						}
					}
				} 
				if(this.GetType().GetProperty((String)((DictionaryEntry)enumerator.Current).Key) != null)
				{
					string variable = "m_" + (String)((DictionaryEntry)enumerator.Current).Key;
					if((fInfo = thisType.GetField(variable, BindingFlags.DeclaredOnly|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance)) != null)
					{
							fInfo.SetValue(this, ((DictionaryEntry)enumerator.Current).Value);
					}
				}
			}
		}
#endregion

#region Methods
		public override void addOrderDetail(OrderDetail od)
		{
			if(od != null)
			{
				od.Order = this;
				m_OrderDetails.Add(od);
			}
			else
			{
				throw new ApplicationException();
			}
		}
		
		public override void delete()
		{
			foreach(OrderDetail orderdetail in OrderDetails)
			{
				orderdetail.delete();
			}
			
			this.markRemoved();
		}
#endregion

#region Properties
		public override Int32 OrderId 
		{
			get
			{
				if(m_id == null)
					return 0;			
				return (Int32)m_id[0];
			}
		}
		public override Person Person 
		{
			get
			{
				return (Person)m_Person.Object;
			}
			set
			{
				m_Person.Object = value;
			}
		}
		public override DateTime OrderDate 
		{
			get
			{
				if(m_OrderDate == null)
					return new DateTime(0);			
				return (DateTime)m_OrderDate;
			}
			set
			{
				m_OrderDate = value;
				markDirty();
			}
		}
		public override DateTime ShippedDate 
		{
			get
			{
				if(m_ShippedDate == null)
					return new DateTime(0);			
				return (DateTime)m_ShippedDate;
			}
			set
			{
				m_ShippedDate = value;
				markDirty();
			}
		}
		public override String OrderState 
		{
			get
			{
				if(m_OrderState == null)
					return String.Empty;			
				return (String)m_OrderState;
			}
			set
			{
				m_OrderState = value;
				markDirty();
			}
		}
		public override IList OrderDetails 
		{
			get
			{
				return (IList)m_OrderDetails;
			}
		}
				
		public static FactoryImpl Factory
		{
			get
			{
				return m_FactoryImpl;
			}
		}
		
		public static FinderImpl Finder
		{
			get
			{
				return m_FinderImpl;
			}
		}
		
		public override bool isNull(string propertyName)
		{
			switch(propertyName)
			{
				case "Person":
					if(m_Person.Object == null) return true;
					break;
				case "OrderDate":
					if(m_OrderDate == null) return true;
					break;
				case "ShippedDate":
					if(m_ShippedDate == null) return true;
					break;
				case "OrderState":
					if(m_OrderState == null) return true;
					break;
				default:
					break;
			}
			return false;
		}
#endregion
	}

}
