//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//     Version: 2.2.7.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Reflection;
using Storm.Lib;
using Storm.Attributes;
using HsrOrderApp.BusinessLayer.DomainModel;

namespace HsrOrderApp.BusinessLayer.DomainModelImpl
{

	[DomainObjectImpl]
	public class PersonImpl : Person
	{
#region Factory Implementation
		public class FactoryImpl : PersonFactory, IFactory
		{ 
			public override Person createPerson(String name, String password)
			{
				return new PersonImpl(name, password);
			}
			
			public DomainObject create()
			{
				return new PersonImpl();
			}
			
			public DomainObject createFromParameters(
				Key id,
				Timestamp timestamp,
				params DictionaryEntry[] parameters)
			{
				return new PersonImpl(id, timestamp, parameters);
			}
		}
#endregion

#region Finder Implementation
		public class FinderImpl : PersonFinder, IFinder
		{
			public override IList findByNameAndPassword(String name, String password)
			{
				QueryObject qo = new QueryObject();
				qo.addCriteria(new Criteria(Criteria.Operator.Equal, "Password", password));
				qo.addCriteria(new Criteria(Criteria.Operator.Equal, "Name", name));

				return Registry.Instance.getMapper(typeof(Person)).find(qo);
			}
			public override IList findByName(String name)
			{
				QueryObject qo = new QueryObject();
				qo.addCriteria(new Criteria(Criteria.Operator.Equal, "Name", name));

				return Registry.Instance.getMapper(typeof(Person)).find(qo);
			}
			public DomainObject findById(Key id)
			{
				return Registry.Instance.getMapper(typeof(Person)).findById(id);
			}
			public IList find(QueryObject qo)
			{
				return Registry.Instance.getMapper(typeof(Person)).find(qo);
			}
			public IList findAll()
			{
				return Registry.Instance.getMapper(typeof(Person)).findAll();
			}
		}
#endregion

#region Static Attributes
		private static FactoryImpl m_FactoryImpl = new FactoryImpl();
		private static FinderImpl m_FinderImpl = new FinderImpl();
#endregion
		
#region Member Variables
		private object m_Name = null;
		private object m_Password = null;
		private ToManyRelation m_Addresses = null;
		private ToManyRelation m_Orders = null;
#endregion

#region Constructors
		public PersonImpl()
		{
		}
		
		public PersonImpl(String name, String password)
		{
			markNew();
			m_Addresses = new ToManyRelation(typeof(Address), "PersonID", null, true);
			m_Orders = new ToManyRelation(typeof(Order), "PersonID", null, true);
			m_Password = password;
			m_Name = name;
		}

		internal PersonImpl(
			Key id, 
			Timestamp timestamp, 
			params DictionaryEntry[] parameters)
		{ 
			markClean();
			m_id = id;
			m_timestamp = timestamp;
			FieldInfo fInfo;
			Type thisType = this.GetType();
			Type domainObjectType = typeof(Person);
			
			IEnumerator enumerator = parameters.GetEnumerator();

			while(enumerator.MoveNext())
			{
				if(((DictionaryEntry)enumerator.Current).Value != null)
				{
					if(((DictionaryEntry)enumerator.Current).Value.GetType() == typeof(ToOneRelation))
					{ 
					} 
					if(((DictionaryEntry)enumerator.Current).Value.GetType() == typeof(ToManyRelation))
					{ 
						if((String)((DictionaryEntry)enumerator.Current).Key == "Addresses")
						{ 
							m_Addresses = (ToManyRelation)((DictionaryEntry)enumerator.Current).Value;
							continue;
						}
						if((String)((DictionaryEntry)enumerator.Current).Key == "Orders")
						{ 
							m_Orders = (ToManyRelation)((DictionaryEntry)enumerator.Current).Value;
							continue;
						}
					}
				} 
				if(this.GetType().GetProperty((String)((DictionaryEntry)enumerator.Current).Key) != null)
				{
					string variable = "m_" + (String)((DictionaryEntry)enumerator.Current).Key;
					if((fInfo = thisType.GetField(variable, BindingFlags.DeclaredOnly|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance)) != null)
					{
							fInfo.SetValue(this, ((DictionaryEntry)enumerator.Current).Value);
					}
				}
			}
		}
#endregion

#region Methods
		public override void addOrder(Order o)
		{
			if(o != null)
			{
				o.Person = this;
				m_Orders.Add(o);
			}
			else
			{
				throw new ApplicationException();
			}
		}
		public override void addAddress(Address a)
		{
			if(a != null)
			{
				a.Person = this;
				m_Addresses.Add(a);
			}
			else
			{
				throw new ApplicationException();
			}
		}
		
		public override void delete()
		{
			foreach(Address address in Addresses)
			{
				address.delete();
			}
			foreach(Order order in Orders)
			{
				order.delete();
			}
			
			this.markRemoved();
		}
#endregion

#region Properties
		public override Int32 PersonId 
		{
			get
			{
				if(m_id == null)
					return 0;			
				return (Int32)m_id[0];
			}
		}
		public override String Name 
		{
			get
			{
				if(m_Name == null)
					return String.Empty;			
				return (String)m_Name;
			}
			set
			{
				m_Name = value;
				markDirty();
			}
		}
		public override String Password 
		{
			get
			{
				if(m_Password == null)
					return String.Empty;			
				return (String)m_Password;
			}
			set
			{
				m_Password = value;
				markDirty();
			}
		}
		public override IList Addresses 
		{
			get
			{
				return (IList)m_Addresses;
			}
		}
		public override IList Orders 
		{
			get
			{
				return (IList)m_Orders;
			}
		}
				
		public static FactoryImpl Factory
		{
			get
			{
				return m_FactoryImpl;
			}
		}
		
		public static FinderImpl Finder
		{
			get
			{
				return m_FinderImpl;
			}
		}
		
		public override bool isNull(string propertyName)
		{
			switch(propertyName)
			{
				case "Name":
					if(m_Name == null) return true;
					break;
				case "Password":
					if(m_Password == null) return true;
					break;
				default:
					break;
			}
			return false;
		}
#endregion
	}

}
