//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//     Version: 2.2.7.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Reflection;
using System.Text;
using System.Data;
using System.Data.SqlClient;
using Storm.Lib;
using Storm.Attributes;
using NorthWind;

namespace NorthWind
{


	[MapperImpl(typeof(EmployeeTerritory))]
	public class EmployeeTerritoryMapper : IMapper
	{		
#region Finder Methods
		public DomainObject findById(Key id)
		{
			try
			{
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from EmployeeTerritories WHERE EmployeeID = @Employee AND TerritoryID = @Territory";
				SqlCommand command = new SqlCommand(sqlStmt, connection);
				command.Parameters.Add("@Employee", id[0]);
				command.Parameters.Add("@Territory", id[1]);

				reader = command.ExecuteReader();
				EmployeeTerritory employeeterritory = null;
				if(reader.Read())
				{
					employeeterritory = loadFields(reader);
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return employeeterritory;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList findAll()
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from EmployeeTerritories";
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		

		public IList find(QueryObject qo)
		{
			try
			{
				ArrayList array = new ArrayList();
				SqlDataReader reader = null;
				SqlConnection connection = UnitOfWork.Instance.Connection;

				connection.Open();

				string sqlStmt = 
					"SELECT * from EmployeeTerritories WHERE " + qo.ToString();
				SqlCommand command = new SqlCommand(sqlStmt, connection);

				reader = command.ExecuteReader();
				while(reader.Read())
				{
					array.Add(loadFields(reader));
				} 
				if(reader != null)
					reader.Close();
				connection.Close();

				return array;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}		
#endregion		
		
#region IMapper Members
		public void insert(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				EmployeeTerritory employeeterritory = (EmployeeTerritory)subject;
				SqlCommand command = new SqlCommand(
					"INSERT INTO EmployeeTerritories (TerritoryID, EmployeeID) VALUES (@Territory, @Employee) ; SELECT VersionId FROM EmployeeTerritories WHERE EmployeeID= @Employee AND TerritoryID= @Territory",
					connection, transaction);

				if(subject.isNull("Territory") || employeeterritory.Territory.isNull("TerritoryId"))
				{
					command.Parameters.Add("@Territory", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Territory", employeeterritory.Territory.TerritoryId);
				}
				if(subject.isNull("Employee") || employeeterritory.Employee.isNull("EmployeeId"))
				{
					command.Parameters.Add("@Employee", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Employee", employeeterritory.Employee.EmployeeId);
				}
				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					employeeterritory.Timestamp = safeGetTimestamp(reader);
					subject.FireIdChanged();
					reader.Close();			
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void update(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				EmployeeTerritory employeeterritory = (EmployeeTerritory)subject;
				SqlCommand command = new SqlCommand(
					"UPDATE EmployeeTerritories SET  WHERE EmployeeID = @Employee AND TerritoryID = @Territory AND VersionId = @VersionId IF @@ROWCOUNT > 0  BEGIN SELECT VersionId FROM EmployeeTerritories WHERE EmployeeID = @Employee AND TerritoryID = @Territory END",
					connection, transaction); 

				command.Parameters.Add("@VersionId", employeeterritory.Timestamp.Value);
				if(subject.isNull("Employee") || employeeterritory.Employee.isNull("EmployeeId"))
				{
					command.Parameters.Add("@Employee", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Employee", employeeterritory.Employee.Id[0]);
				}
				if(subject.isNull("Territory") || employeeterritory.Territory.isNull("TerritoryId"))
				{
					command.Parameters.Add("@Territory", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Territory", employeeterritory.Territory.Id[0]);
				}

				SqlDataReader reader = command.ExecuteReader();
				if(reader.Read())
				{
					employeeterritory.Timestamp = safeGetTimestamp(reader);
					reader.Close();
				}
				else
				{
					reader.Close();
					throw new ConcurrencyException();
				}
				subject.FireIdChanged();

			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public void delete(DomainObject subject, SqlConnection connection, SqlTransaction transaction)
		{
			try
			{
				EmployeeTerritory employeeterritory = (EmployeeTerritory)subject;
				
				SqlCommand command = new SqlCommand(
					"DELETE FROM EmployeeTerritories WHERE EmployeeID = @Employee AND TerritoryID = @Territory AND VersionId = @VersionId",
					connection, transaction);

				command.Parameters.Add("@VersionId", employeeterritory.Timestamp.Value);
				if(subject.isNull("Employee") || employeeterritory.Employee.isNull("EmployeeId"))
				{
					command.Parameters.Add("@Employee", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Employee", employeeterritory.Employee.Id[0]);
				}
				if(subject.isNull("Territory") || employeeterritory.Territory.isNull("TerritoryId"))
				{
					command.Parameters.Add("@Territory", DBNull.Value );
				}
				else
				{
					command.Parameters.Add("@Territory", employeeterritory.Territory.Id[0]);
				}
				if(command.ExecuteNonQuery() <= 0)
				{
					throw new ConcurrencyException();
				}
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
		}
		
		public DomainObject ResolveToOneRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			SqlConnection connection = UnitOfWork.Instance.Connection;
			
			connection.Open();

			try
			{
				String selectStmt = "SELECT * FROM EmployeeTerritories WHERE " + fieldName + " = @FK";
				SqlCommand command = new SqlCommand(selectStmt, connection);
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				EmployeeTerritory employeeterritory = null;
				
				if(reader.Read())
				{
					employeeterritory = loadFields(reader);
				}
				if(reader != null)
				{
					reader.Close();
				}
				connection.Close();
				
				return employeeterritory;
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
		}
		
		public IList ResolveToManyRelation(Key id, String fieldName)
		{
			SqlDataReader reader = null;
			ArrayList array = new ArrayList();
			SqlConnection connection = UnitOfWork.Instance.Connection;
			SqlCommand command;
			connection.Open();
			
			try
			{
				command = new SqlCommand(
					"SELECT EmployeeID, TerritoryID, VersionId FROM EmployeeTerritories WHERE " + fieldName + " = @FK", connection);
					
				command.Parameters.Add("@FK", id[0]);
				
				reader = command.ExecuteReader();
				ArrayList keys = new ArrayList();
				Timestamp timestamp;
				while(reader.Read())
				{ 
					object employee = safeGetValue(reader, "EmployeeID");
					object territory = safeGetValue(reader, "TerritoryID");
					
					timestamp = safeGetTimestamp(reader);
					
					Key currentKey = new Key(new object[]{employee, territory});
					DomainObject domobj = UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(
						typeof(EmployeeTerritory), currentKey);
					
					if(domobj == null)
					{
						keys.Add(currentKey);
					}
					else if(!domobj.Timestamp.Equals(timestamp))
					{
						UnitOfWork.Instance.IdentityMap.unregisterDomainObject(domobj);
						keys.Add(currentKey);
					}
					else
					{
						array.Add(domobj);
					}
				}
				reader.Close();

				if(keys.Count > 0)
				{
					int primKeysCount = 2;
					ArrayList primKeys = new ArrayList();
					primKeys.Add("EmployeeID");
					primKeys.Add("TerritoryID");
					StringBuilder selectAdStmt = new StringBuilder();
					selectAdStmt.Append("SELECT * FROM ");
					selectAdStmt.Append("EmployeeTerritories");
					selectAdStmt.Append(" WHERE ");
					StringBuilder whereStmt;
					String[] andStmts = new String[keys.Count];
					for(int i = 0; i < keys.Count; i++)
					{
						String[] primKeyCriterias = new String[primKeysCount];
						for(int j = 0; j < primKeysCount; j++)
						{
							primKeyCriterias[j] = primKeys[j] + " = @key" + i +j;
						}
						whereStmt = new StringBuilder();
						whereStmt.Append("(");
						whereStmt.Append(String.Join(" AND ", primKeyCriterias));
						whereStmt.Append(")");
						andStmts[i] = whereStmt.ToString();
					}
					selectAdStmt.Append(String.Join(" OR ", andStmts));
					
					command = new SqlCommand(
						selectAdStmt.ToString(), connection);
					for(int i = 0; i < keys.Count; i++)
					{
						for(int j = 0; j < primKeysCount; j++)
						{
							String keyParam = "@key" + i + j;
							command.Parameters.Add(keyParam, ((Key)keys[i])[j]);
						}
					}
					
					reader = command.ExecuteReader();
					
					while(reader.Read())
					{
						EmployeeTerritory employeeterritory = loadFields(reader);
						array.Add(employeeterritory);
					}
					reader.Close();
				} 
			}
			catch(SqlException sqle)
			{
				throw new ApplicationException(sqle.Message);
			}
			catch(Exception e)
			{
				throw new ApplicationException(e.Message);
			}
			finally
			{
				connection.Close();
			}
			return array;
		}
#endregion		

#region Helper Methods
		public EmployeeTerritory loadFields(SqlDataReader reader)
		{
			Timestamp m_timestamp = safeGetTimestamp(reader);
			Key m_key = new Key(new object[]{
				safeGetValue(reader, "EmployeeID"),
				safeGetValue(reader, "TerritoryID")
			});

		
			EmployeeTerritory employeeterritory = 
				(EmployeeTerritory)UnitOfWork.Instance.IdentityMap.getDomainObjectIfLoaded(typeof(EmployeeTerritory), m_key);
			
			if(employeeterritory == null)
			{
				employeeterritory = 
					(EmployeeTerritory)Registry.Instance.getFactory(typeof(EmployeeTerritory)).createFromParameters(
						m_key,
						m_timestamp,
						new DictionaryEntry("Employee", new ToOneRelation(typeof(Employee), "EmployeeID", new Key(new object[] { safeGetValue(reader, "EmployeeID")}))),
						new DictionaryEntry("Territory", new ToOneRelation(typeof(Territory), "TerritoryID", new Key(new object[] { safeGetValue(reader, "TerritoryID")}))));
				
				UnitOfWork.Instance.IdentityMap.registerDomainObject(employeeterritory);
			}
			return employeeterritory;
		}

		protected Timestamp safeGetTimestamp(SqlDataReader reader)
		{
			byte[] m_buffer = new byte[8];
			reader.GetBytes(reader.GetOrdinal("VersionId"), 0, m_buffer, 0, 8);
			return new Timestamp(m_buffer);
		}
		
		protected object safeGetString(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : reader.GetString(ordinal).Trim();
		}
		
		protected object safeGetDouble(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDouble(ordinal);
		}
		
		protected object safeGetInt32(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetInt32(ordinal);
		}
		
		protected object safeGetDateTime(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetDateTime(ordinal);
		}

		protected object safeGetValue(SqlDataReader reader, string columnName)
		{
			int ordinal = reader.GetOrdinal(columnName);
			return reader.IsDBNull(ordinal) ? null : (object)reader.GetValue(ordinal);
		}
#endregion

	}
}
